export const NOTIFICATION = {
  ERROR_GETTING_FAVOURITES: 'Http failure response for getting favorites weather',
  ERROR_SEARCHING_LOCATION: 'Error while searching location',
  ERROR_GETTING_WEATHER: 'Http failure response for getting weather',
  ERROR_GETTING_FORECAST: 'Http failure response for getting forecast',
  ERROR_GETTING_LOCATION: 'Http failure response for getting location',
  ERROR_DIALOG_FAVORITES: `You don't have any favorites to remove`,
  ERROR_UPDATING_WEATHER: (name: string): string => `Http failure response for updating weather in ${name}`,
  ERROR_UPDATING_FAVOURITES: 'Http failure response for updating favorites weather',
  SUCCESS_UPDATING_FAVOURITES: 'Success updating all favorites weather',
  SUCCESS_ADDING_FAVOURITE: (name: string) => `Success adding ${name} location to favorite list`,
  SUCCESS_REMOVING_FAVOURITE: (name: string) => `Success removing ${name} location from favorite list`,
  SUCCESS_UPDATING_WEATHER: (name: string): string => `The weather in ${name} has been successfully updated`,
  SUCCESS_DIALOG_FAVORITES: 'Success removing all favorites',
};
